#!/bin/bash
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/scripts" "$HOME/Scripts"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"

for i in vim tmux; do
  cd $i && sh setup
  cd -
done
