#!/bin/bash

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"

# Install Pathogen
#mkdir "$HOME/.vim/" "$HOME/.vim/autoload" "$HOME/.vim/bundle" && \
#curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

#cd ~/.vim/bundle
#git clone git://github.com/altercation/vim-colors-solarized.git

#ln -sf "$PWD/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
